version: '2.1'
jobs:
  test: &test-defaults
    docker:
      - image: alpine/git:latest

    shell: /bin/sh -leo pipefail

    environment:
      BASH_ENV: /etc/profile

    steps:
      - checkout

      - run:
          name: Download Golang
          command: |
            wget https://go.dev/dl/go1.19.3.linux-amd64.tar.gz
      
      - run:
          name: Install Golang
          command: |
            tar -C /usr/local -xzf go1.19.3.linux-amd64.tar.gz

      - run:
          name: Add Golang to PATH
          command: |
            echo 'export PATH=/usr/local/go/bin:"$PATH"' >> "$BASH_ENV"

      - run:
          name: Run tests
          command: |
            go test ./...

  test-2_36_3:
    <<: *test-defaults
    docker:
      - image: alpine/git:2.36.3
  test-1_0_35:
    <<: *test-defaults
    docker:
      - image: alpine/git:1.0.35
workflows:
  test_and_deploy:
    jobs:
      - test-2_36_3:
          filters:
              tags:
                only: /^v.*/
      - test-1_0_35:
          filters:
              tags:
                only: /^v.*/
